### ISSUE TITLE
Trouble Sending in variables to a room

### ISSUE THREAD

**Issue by BLCSoftware** [alvyxaz/barebones-masterserver#102]
trying to send in a password for private rooms do not seem to be set, and trying to send in other variables i cant seem to get the get them to get set either, only the name and max number are stored. 

this is how I'm sending in the information:
```
 var settings = new Dictionary<string, string>
            {
                {MsfDictKeys.MaxPlayers, maxPlayers.ToString()},
                {MsfDictKeys.RoomName, name},
                {MsfDictKeys.Blinds, blind.ToString()},
                {MsfDictKeys.RoomPassword, pass},
                {MsfDictKeys.IsPublic, true.ToString() },
                {MsfDictKeys.SceneName, "CustomGame"}
            };

            Msf.Client.Spawners.RequestSpawn(settings, "", (requestController, errorMsg) =>
            {
                if (requestController == null)
                {
                    ProgressUi.gameObject.SetActive(false);
                    Msf.Events.Fire(Msf.EventNames.ShowDialogBox,
                        DialogBoxData.CreateError("Failed to create a game: " + errorMsg));

                    Logs.Error("Failed to create a game: " + errorMsg);
                }

                ProgressUi.Display(requestController);
            });
```

**Comment by alvyxaz** [comment]
Hey! Thanks for reporting this

I just tested and replicated the issue - I'll get back with a fix within an hour ;)

**Comment by alvyxaz** [comment]
Alright, so I've fixed the passwords. As I understand, you've slightly modified the framework code, so here's a commit I made. Try to replicate the changes from this commit (accidentally named it "Pixel" instead of "Fixed", haha):
[https://github.com/alvyxaz/barebones-masterserver/commit/4126ea3090ee67c3895d2959992d1c1fddb81d30](https://github.com/alvyxaz/barebones-masterserver/commit/4126ea3090ee67c3895d2959992d1c1fddb81d30)

Regarding sending data to a spawned room,  a lot depends on where you want to access the data: on client, or on the spawned game server, or somewhere else?

In general, spawning a game server works like this:
1. Unity process is started
2. It connects to master and retrieves all of the provided properties
3. It Registers a room (creates new dictionary of properties - you can't send the same one from spawn properties, because it might contain secret data)

I made another commit: https://github.com/alvyxaz/barebones-masterserver/commit/28bb99cedf46beaf92619ce2a9dfbb755e753240

You should be able to access spawn properties in `UnetGameRoom.BeforeSendingRegistrationOptions()` method. You can override it, and use it to modify room options before sending room registration request.

Cheers!

**Comment by BLCSoftware** [comment]
ok after making the changes, while creating the room on a WebGL version with web-sockets it seems that the password gets set but trying to join as the creator, it does not send in the password, but trying to join the table from another instance does work.

**Comment by alvyxaz** [comment]
You made the changes in `CreateGameProgressUi.cs` from commit https://github.com/alvyxaz/barebones-masterserver/commit/4126ea3090ee67c3895d2959992d1c1fddb81d30 ?

If so, room creator should be able to join.

Was it not working on WebGL only? Sometimes, browser caches a previous version, so that might have been the issue :)

**Comment by BLCSoftware** [comment]
the passwords are working perfectly, thank you, the issue seemed to be with the server acting up. but i cant access the properties in scene, i tried what was in the Rooms API example but the access received never fired. i would prefer if it was done server-side also.

**Comment by BLCSoftware** [comment]
i figured it out i also had to add it to BeforeRegisteringRoom on my UnetGameRoom

**Comment by alvyxaz** [comment]
Really great to hear that!
