### ISSUE TITLE
Creating room is stuck at 3/5

### ISSUE THREAD

**Issue by fgurel** [alvyxaz/barebones-masterserver#107]
Hi,

I have modified Quick Demo to work with my own scene, but now when client creates a room GameServer is started but client is stuck ad GameProgress 3/5 (WaitingForProcess). So is it stuck at registering the game to GameServer? 

Thank you,
Gurel

**Comment by jim-freeman** [comment]
Read the log output for your various processes. Sounds like a null-ref on the master server during room registration.

--angusmf

**Comment by fgurel** [comment]
Hi,
Thank you for the answer. Do you have any suggestions on which scripts I should look?

Gurel

**Comment by angusmf** [comment]
No, so I suggested looking at your log files. If you are testing using windows standalone builds, there should be subfolder in the same folder as your executable named [executable name]_Data and inside that is a file named output_log.txt. I suggest you start by looking in those files for null reference errors (NullReferenceException: Object reference not set to an instance of an object)
You will be able to tell exactly what line in what file had the reference error, if any.

**Comment by fgurel** [comment]
Hi again,

I've checked all three logs for masterandspawner, gameserver and client but there seems to be no error indicating null reference. Actually there are no errors in any except MasterAndSpawner but they are there when it tries to create the spawner which, after a while, result in Spawner successfully created. Id: 0 so that's not a problem I guess. 

I cannot fully comprehend the big picture of the framework, so maybe I am doing  something wrong when I try to change the Quick Demo since it works just fine. But with my scenes etc it is stuck at 3/5.

**Comment by alvyxaz** [comment]
Are you trying to run it on a local computer, or on a server :)?

**Comment by alvyxaz** [comment]
When you've mentioned that `GameServer is started` , did you mean the actual game server (Unet game server, with specific port open), or just a **Unity executable**, which should become a game server later on?

At the moment, I'll assume the latter.

Alright, so as you've guessed, if it's stuck at 3/5, it means that:
* Unity instance (process) is spawned
* It **doesn't** register to the master server

Of the top of my head, here are the things that should happen to fully complete the process of spawning a game server:
1. Unity exe starts - make sure you don't spawn servers in batchmode, so that you can verify that a process is spawned
1. Connects to master server
1. Switches to appropriate scene (you'll be able to see this, if you don't spawn games in batchmode). If this is a problem, it's likely that you don't handle the scene switching in your main scene. You can find an example of this in file `QuickGameServerScene.cs`. You can use the same file to verify if game server successfully connects to master
1. This scene should have a `UnetServerStarter`, in which:
   1. `OnConnectedToMaster()` is called (you can do `Debug.LogError("I'm here")` to make sure it get's there, don't forget to build with "DevelopmentBuild" flag, otherwise you won't see the logs)
   1. Determines if this is a spawned process and calls `StartSpawned()`, again, you can log something out to see if you get there
       1. Within that method, it calls `Msf.Server.Spawners.RegisterSpawnedProcess` and "Registers" the process. This actual should get you from **3/5** to **4/5**

Try to go through this list, and let me know how it goes.

Cheers!

**Comment by fgurel** [comment]
Hello,

Thank you for the answer. So far I am running the server on the local machine and yes GameServer.exe starts running as you have correctly assumed, and it actually loads the scene I want but that's it. Client side is stuck. I will now follow the steps you have given to check and debug what I might have done wrong. 

Thank you again,
Gurel

**Comment by fgurel** [comment]
Hello again,

You are right it doesn't receive the scene argument. I have verified that it actually gets in OnConnectedToMaster but then GameServer does not load the scene. The reason that it did before was I have accidentally put the scene before GameServer scene in build :S 

I only give the scene as the parameter of CreateGameUI under maps and that's it. Should I be doing something else too?

Thank you!

**Comment by fgurel** [comment]
I got it now, thank you!

Turns out that I have commented some parts out when I was trying to understand the demo and then forgotten to uncomment them. Debugging step by step helped me find these. 

Sorry for the inconvenience and thank you so much!
Gurel

**Comment by alvyxaz** [comment]
Good to hear that you've got it working! ;)
