### ISSUE TITLE
Can't reach my server with public ip but work with local ip

### ISSUE THREAD

**Issue by tatien** [alvyxaz/barebones-masterserver#13]
Hi @alvyxaz,

Today, I tried to host the master server on a VPS, but the client wasn't able to reach the server with the public IP. When I tried to connect with the public IP the unity instance freeze for something like 30 seconds. I tried with both servers Linux and Windows with the demo.  

I also tried on my local network and this time it work's with the local IP but not with the public IP. (For testing purpose I open all the port for TCP and UDP without effect.)

**Comment by alvyxaz** [comment]
Hey!

That's strange. Did you change these values at Barebones > Connection object (in the hierarchy)?

![](http://i.imgur.com/pvxNKxg.png)

**Comment by tatien** [comment]
Yes, both of them.

**Comment by alvyxaz** [comment]
Can you turn on the master server, and send me an e-mail with its address? My e-mail is alvyxaz@gmail.com

**Comment by tatien** [comment]
I don't know why, but it's look like the issue come from my local network, because I succeed to reach my server with my mobile connection.

.
Right now I can connect to my master but not to the GameServer.
When try to create a room the player didn't spawn (see client screenshot below).
<img width="1277" alt="capture d ecran 2016-12-12 a 00 37 17" src="https://cloud.githubusercontent.com/assets/16664220/21084465/72825040-c004-11e6-8797-9d2e012cdf60.png">
On the second try I can't create a GameServer : I got Game creation aborted (progress : 2/5)

**Comment by alvyxaz** [comment]
From the screenshot, it seems like the client is trying to connect to local host, instead of the public ip address.

This happens when game server doesn't know it's own public IP. To fix that, you can add an extra parameter to the command line arguments of spawner server "-bmIp xx.xx.xx.xx"

Do you still get the error when creating a second game server?

**Comment by tatien** [comment]
Thanks, this solved my problem.

**Comment by fgurel** [comment]
#Hi,

I am receiving the same error.  I give the ip adress of my server, use port 5000 for Client, GameServer and MasterAndSpawner scenes' ConnectionToMaster. I also change the default exe path to ./GameServer.x86_64 in Spawner object MasterAndSpawner scene. Yet I obtain the same screenshot, it still says connecting to 127.0.0.1:5000. Having received this I also fixed the ip adress in ConnectionToMaster script yet still nothing changes. Using -bmpIp too does not change anything at all. Result is, client connects to master, yet after a succesful room creation game returns back to Game Creation menu scene with error 

ClientDisconnected due to error: Timeout
UnityEngine.Networking.NetworkIdentity:UNetStaticUpdate()

Can anyone help?
