### ISSUE TITLE
Second Client in a lobby not getting lobby screen

### ISSUE THREAD

**Issue by jeff-odg** [alvyxaz/barebones-masterserver#14]
Hello,

I just purchased the Master Server assets and I have been working through the Demos. I have found that when I test the lobby system (which is going to be a fundamental part of my game) the second client joining the lobby does not get the lobby screen shown.  They show up in the lobby, and everything else updates correctly. 

I am just building the MainEmpty scene and running it at this point.

 What am I doing wrong?

Let me know!

Jeff

**Comment by alvyxaz** [comment]
Hey!

First of all - thanks a lot for the purchase!

I've just recreated the problem. Apparently, when copying the scene, I forgot to set the `LobbyView` property of the `MainScreen` component.

In the hierarchy, select canvas, and drag the lobby object into the `MainScreen` component's `LobbyView` field:

![image](https://cloud.githubusercontent.com/assets/3227731/21105472/fe7cda78-c092-11e6-8a0b-23f1d0ca0c7a.png)

Does this resolve the issue?

By the way, you can build the client with **Development Build** flag selected, so that you can see error messages ;)

**Comment by jeff-odg** [comment]
That fixed the issue.. Thanks for the quick response!

Jeff
http://www.opaldragonflygames.com/
