### ISSUE TITLE
Npgsql DLL Not working in editor

### ISSUE THREAD

**Issue by salokinsomisa** [alvyxaz/barebones-masterserver#143]
I've implemented the basic postgreSQL database that came with the asset. I run the server in a build and everything's working fine. But when I'm trying to run the Server in the editor ( as I'm trying to understand how this asset works and implement different things), Unity gives me a MissingMethodException when it's calling the AddWithValue method through the Npgsql library. 
I understand that the aforementioned exception can happen when the library isn't found or when you're giving the method wrong arguments (Perhaps I'm getting something wrong here). The connection to the database seems to happen, since it doesn't give any errors there. 
So, my question is. Why is it that such an exception is thrown only in the Editor while the final build is working fine?

Error logged in Editor:
MissingMethodException: Method not found: 'Npgsql.NpgsqlParameterCollection.AddWithValue' 
(This particular exception happens when I'm trying to log in/ Or more specifically, when the Authorization module tries to access the GetAccount function in the AuthDbPostgreSQL.cs. I haven't tried to test it with any other methods)

**Comment by nicolapattigithub** [comment]
Hello salokinsomisa,  
I had the same problem as yours. I Tried almost everything to figure out what caused the issue. At the end, I found a solution but I don't know why it works (maybe someone can tell us). To fix the problem let's take the Npgsql.dll and put it into the Asset folder (so you have the file into \Asset\Npgsql.dll). In my case, I've copied even the System.Data.dll for another error. 
Now everything works fine in my case.

Let me know if the tip resolved your problem

**Comment by salokinsomisa** [comment]
Thanks a lot for replying! Unfortunately, it hasn't worked. I found a way around it though. It seems that the DLL is working for me as long as I upgrade to .NET 4.6 . The problem is that by upgrading it, your Editor starts working again but your build fails. Now I can only run it in the editor.
Furthemore, due to different .NET versions some scripts behave differently.

This is quite nervewracking to say the least.

**Comment by nicolapattigithub** [comment]
Hi solokinsomisa,
I don't know if you fixed the problem, I've installed Unity 2017 on VPS and I've got again the error:
MissingMethodException: Method not found: 'Npgsql.NpgsqlParameterCollection.AddWithValue'

reading the build log I noticed that the Libraries Npgsql.dll and Mono.Security.dll were loaded from two paths:
the first one from the path 
C:\Program Files\Unity2017\Editor\Data\Mono\lib\mono\2.0\Npgsql.dll
AND the second from the path:
C:\<PROJECT PATH>\MasterServer_2017\Assets\Barebones\MsfDatabaseImplementations\PostgreSQL\Plugins\Npgsql.dll

These are in conflict for sure, because of the DLL inside the mono\2.0\
is ver 2.0.0 and the one which is compatible with PostgreDB is ver 2.2.7

To solve the problem I've copied the newest DLL located inside the path project into the path mono\2.0\ 

Now the master server works both in Editor and build. 

Hope this could help.

**Comment by alexpareto** [comment]
An alternative is to use this package instead as well: https://github.com/mguillemot/UnityNpgsql. Which changes the namespace to UnityNpgsql to avoid conflicts with the old Npgsql.dll used in the editor domain.

**Comment by ghost** [comment]
Wow, thank you both for your comments. I never guessed that there would be that kind of path conflict. What is Npgsql.dll doing in Unity's default libraries? Anyway, thanks a ton!
