### ISSUE TITLE
Client Demo

### ISSUE THREAD

**Issue by jeff-odg** [alvyxaz/barebones-masterserver#15]
Do you have an example of just a client without the Master Server or Game Server code in it? I understand why you combine them all into one for development sake, but as I am learning how all the pieces work, it would be handy to have a client only demo project to look at.

Any help would be appreciated.. and thanks for the amazing framework!

Jeff

**Comment by alvyxaz** [comment]
At the moment, I don't have an example for a client separated from server, mainly because there are no rules on how to do it - it all depends on what's convenient for developer.

It's not what you're asking, but you can check out this post, it contains some information on how the separation could be achieved:
https://forum.unity3d.com/threads/master-server-framework.430570/#post-2829048

And thanks for the compliment ;)
