### ISSUE TITLE
Can barebones do map/scene changes?

### ISSUE THREAD

**Issue by skinnymeat** [alvyxaz/barebones-masterserver#26]
I'm trying to decide about purchasing your asset and I can't tell if it can do map changes for users in either the Game Server or Create Lobby. Pretend a round ends in a multiplayer game then the next map loads for all the players. Can barebones do this?

**Comment by alvyxaz** [comment]
Hey!

You can do it, but it doesn't come "out of the box", so you would need to implement it yourself.

There are multiple ways to do it. For my game, here's how I'm going to do it:

1. Match ends
1. Start a 10 second countdown
1. Game server switches the scene
1. Players also switch the scene 

So this doesn't really have anything to do with the Framework, because scene switching is Unet related. However, it's not very easy to do, as I've heard that there are some bugs related to scene switching in Unet :)
