### ISSUE TITLE
Disconnecting from GameServer

### ISSUE THREAD

**Issue by tophermade** [alvyxaz/barebones-masterserver#29]
I can't seem to find anything on the proper process for disconnecting from a game. I found Logout and such, but no disconnect. Right now players, having left, and up still being registered to the server they left. Could you point me in that direction?

**Comment by alvyxaz** [comment]
Hey!

Are you referring to leaving a master server, or a gamer server?

For game server, since people can use more solutions than just uNet, and they might want to introduce some other mechanics for leaving a game, I decided to "not interfere" and allow developers to handle leaving a game however they want.

However, if you're using uNet, here's how it works on the demo:

* Player clicks a "Stop" button
* He disconnects from a game server
* `EventfulNetworkManager` triggers an event, notifying that user has disconnected from a game server
* `UnetConnector` listens to that event, and invokes `UnetConnector.GoToDisconnectedScene`
* Client switches to another scene

I guess that you won't be using NetworkManagerHud (which has a button to "Stop" client), so you'll want to have a custom button, and leave it when user clicks on it. In that case, call:

`FindObjectOfType<NetworkManager>().StopClient();`

It should disconnect your player from game server. If you have UnetConnector in your game's scene, it will switch to another scene after disconnection. 

If not, something like this should work:

``` C#
        void Awake()
        {
            // Subscribe to "client disconnected" event
            FindObjectOfType<EventfulNetworkManager>().OnClientDisconnectEvent += connection =>
            {
                // Load a specific scene
                SceneManager.LoadScene("SceneName");
            };
        }
```

**Comment by tophermade** [comment]
Whoa, that was remarkably helpful, thanks! I was just looking for a "checkout X file for a direction" and got a full on solution. Super kind, thanks a ton.
