### ISSUE TITLE
Getting started with the demo

### ISSUE THREAD

**Issue by ericmuyser** [alvyxaz/barebones-masterserver#4]
Hey alvyxaz,

I'm finding it unclear how to get started with the asset. There's a few mysterious things:
1. What is with all the hash keys used for the ip/port fields?
2. Which scene is the subprocess suppose to load when you try to create a new game? Command is something like `Starting process with arguments: C:\Users\Eric\Projects\Poseidon\Build\Poseidon.exe  -batchmode -bmStartUserCreated -bmFps 30 -bmInstanceId 1652 -bmMasterKey "" -bmGamePort 1025 -bmIp 127.0.0.1 -bmMasterIp 127.0.0.1 -bmGamesPort 5001 -bmScene "SCENE NAME HERE" `. What is `bmScene` suppose to be? When I started using the asset, it was a random hash on the prefab, I couldn't find it in the editor, so I had to edit the YAML.

I feel like you may have a post-process script that goes in and replaces these with sane values.. and that somehow got skipped in the latest release?

I can reset the asset and give you the exact screenshots, but I didn't because I heavily changed it trying to get it working. Docs don't seem to mention any of the hash stuff or which scene what should be loading, unless I'm missing that?

Thank in advance,
Eric

**Comment by alvyxaz** [comment]
Hey!

Woah, there shouldn't be any hash keys, neither for ip/port fields, nor for anything else. It would be great if you could send me a screenshot of those? This issue was not reported by anyone else, and there are multiple people running their games with the framework, so I think something might have gone wrong when you imported the asset. Or did you mean the "define" syntax (#if UNITY_WEBGL and etc.)?

There are no post-processing scripts involved.

Here's a summary of how the scene is selected:

1. When you make a unity build, in the build settings, you select which scene will be opened by default. This is standard Unity stuff.
2. When you start the "subprocess", unity will open that exact scene first
3. In that "first" scene, there's usually a script which checks if the process was started with "-bmScene" argument. In the demo, this is done in the `GameServerStarter.cs` (`Start()` method, a call to `GetRequiredSceneName()`)
4. Script checks if current scene is the one that we want. If it's not, the scenes are switched.

In essence, framework tries to automate what you would normally do - opens the Game.exe, navigates to a necessary screen and starts a game server.

That's a really weird problem you're having!

**Comment by ericmuyser** [comment]
Oh man. Thanks for the speedy reply. Now I can stop wasting so much time trying to figure out what these hashes are suppose to be and retry import. There's still some left, like this:
![image](https://cloud.githubusercontent.com/assets/156768/19880607/0535bdaa-9fbc-11e6-8b32-2252ce414a23.png)

**Comment by ericmuyser** [comment]
![image](https://cloud.githubusercontent.com/assets/156768/19880621/1d93d7f6-9fbc-11e6-875b-da4798637818.png)

**Comment by ericmuyser** [comment]
Serialization gone wrong...

**Comment by alvyxaz** [comment]
Never seen anything like this!

I think you might need to try and reinstall Unity :/

**Comment by ericmuyser** [comment]
Hey so it works when importing to a new project. Could it be this? 
![image](https://cloud.githubusercontent.com/assets/156768/19880880/43556bec-9fbe-11e6-9e1f-1d83731b455b.png)

**Comment by ericmuyser** [comment]
Aw ya it works man. Yah, it's strange, but if I copy the files from a new project into my existing project, it works. I feel like this is that asset serialization Editor setting, cause I've never seen this before and I've been importing dozens of assets. Unfortunately I needed it for Git tracking. All is working now and it's amazing. Thanks!

**Comment by alvyxaz** [comment]
Awesome, great to hear that! Let me know if you need more help ;)
