### ISSUE TITLE
ClientSocketWs reports IsConnected == true after Disconnect()

### ISSUE THREAD

**Issue by EmilRainero** [alvyxaz/barebones-masterserver#48]
After disconnect, when I try to Connect the clientsocket says it is connected.

My fix

In ClientSocketWs method Disconnect()

Added this to the last line of the method
_isConnected = false;  //EMIL Fix

_isConnected is updated in the Update method, so this may not be the right fix, but it is working for me.

**Comment by alvyxaz** [comment]
Hey! Thanks a lot for reporting this!

There shouldn't be any issues with your fix, and I'll incorporate it to the next update (together with the **//EMIL Fix** comment, haha)

I can't remember why exactly I'm updating the status in Update, rather than retrieving it from the underlying websocket connection. It might be a good idea to revisit core networking wrappers, as I wrote those quite a long time ago.

Thanks again for reporting this!

**Comment by EmilRainero** [comment]
Sure. As my clients get connected to a game they drop the connection to the master server. As the game ends, they reconnect to the master server. 

Having a similar problem with Login. Will report it separately.

**Comment by alvyxaz** [comment]
Why do you want to drop the connection to Master server? At one point, I was designing the framework to work by reconnecting to master when necessary, but that created an extra layer of difficulties for handling states, and with that complexity I probably would have killed most of the customers :).

At the end, I decided it was not worth it, as keeping an idle connection consumes almost no resources (rather than reconnecting, which, with many users reconnecting at the same time, can be a bottleneck)
