### ISSUE TITLE
Timeline for Version 2.0?

### ISSUE THREAD

**Issue by jeff-odg** [alvyxaz/barebones-masterserver#49]
As I was waiting for the docs to be updated so I could use the product and during your updates you needed to do the changes that are 2.0... Do you have a possible release date for 2.0??

Z

**Comment by alvyxaz** [comment]
Hey!

I was hoping to have it released a couple of days ago, but the more I work on it - the more work there seems to be.

I got stuck at the lobbies and making a proper demo. I've planned to make a simple demo, but it's almost impossible to put all of the functionality into something simple.

To answer your question - I think it will take 1-2 days, but I can't be certain, because I keep getting stuck at things :)

Cheers!
