### ISSUE TITLE
Path Finding

### ISSUE THREAD

**Issue by parthshivlab** [alvyxaz/barebones-masterserver#50]
i found the error like this 

-Make sure that your Spawner Server has a correct path to your build

-System.ComponentModel.Win32Exception: ApplicationName='D:/Builds/Win/Build.exe', CommandLine=' -batchmode -bmStartSpawned -bmFps 30 -bmSpawnId 1652 -bmMasterKey "" -bmGamePort 1500 -bmIp 127.0.0.1 -bmMasterIp 127.0.0.1 -bmGamesPort 5001 -bmScene "GameRoom" -bmLobbyId 1', CurrentDirectory=''

**Comment by alvyxaz** [comment]
Open the main scene, Find the Barebones/SpawnerServer object in the hierarchy, and change the "OverrideExePath" to path of your build :)

**Comment by parthshivlab** [comment]
ok but what about device? still not running in my android device. what to do?

**Comment by alvyxaz** [comment]
Do you think you can wait a bit until I finish V2.0? I'll make a good
tutorial then

**Comment by parthshivlab** [comment]
yaa, i will wait, but this is not supported in device??

**Comment by alvyxaz** [comment]
It works on devices, and some people have released games on android too.

You will need to have a master server running somewhere, most likely on VPS
or you computer.

By default, android will try to connect to 127.0.0.1:5000, but this will
not work, because 127.0.0.1 is an address to device itself, not the
computer (or VPS).

You would need to make the android connect to 192.xxx.xxx.xxx (which is a
public address of a local network).

And Android can only work as a client, not master server :)

**Comment by parthshivlab** [comment]
can you plaese once again do connection by team viewer?

**Comment by parthshivlab** [comment]
hyy in desktop build how to set exe path ?

**Comment by parthshivlab** [comment]
hellow are you there?

**Comment by alvyxaz** [comment]
Hey!

I'm really sorry, but I need to focus on finishing V2.0.

If I keep replying to e-mails, I will never finish it. Just wait a bit
until I'm done, and I'll help you out - you shouldn't try using v1.03,
because it will be replaced soon.

**Comment by parthshivlab** [comment]
okkk so when you release it?

**Comment by alvyxaz** [comment]
Hopefully this Sunday (12th) :)
