### ISSUE TITLE
Lobby Not working

### ISSUE THREAD

**Issue by DJCookiez** [alvyxaz/barebones-masterserver#53]
When me and my friend go to test the demo, we go into a lobby and when we start it just says 'Starting Game' and does nothing, i suspect it's something to do with making a game server? but had no idea so i thought i'd make an issue.

**Comment by DJCookiez** [comment]
On an off note, i cannot view my database files due to the fact they're encrypted any help of finding the password?

**Comment by alvyxaz** [comment]
Hey! Again, sorry for replying so late (still focusing on V2, which will be released tomorrow)

Does it not work in lobby, or also when you click on the "Create Game Server"? If it doesn't work in both cases, there's probably something wrong with spawning a game server.

Regarding the database - by default, it's set to use LiteDB, which is an embedded database, which saves data in binary format. LiteDB was added only for a quick setup (so that you don't need to install any databases into your system if you don't want to). If you need to modify the data, you'll need to use another database, like MongoDB or MySQL (support for MySQL comes with V2.0).

And even then, you won't be able to read the password, because stored passwords are encrypted for security reasons (storing literal password is bad practice) ;)

I apologize for all of the inconveniences that you're experiencing. I'll try to make V2.0 a smoother experience :)

**Comment by DJCookiez** [comment]
It's fine, i can't wait for V2 :) and i'll check the spawning services, it runs fine, i can create a lobby we can all join etc, but when we click start game nothing happens, i'll test this again.

**Comment by DJCookiez** [comment]
I added a game server, and i run the master server in the editor and i get this error, 

[Error] 'Game Server Starter' fired a start event, but nothing handled it. Most likely, you have no game server object in the scene
UnityEngine.Debug:LogError(Object)

**Comment by DJCookiez** [comment]
Fixed it all
