### ISSUE TITLE
V2.0 Bugs

### ISSUE THREAD

**Issue by DeadlyCobraXXX** [alvyxaz/barebones-masterserver#57]
These issues are separate from my original post (#55) which pertains to GameServer processes. I'll try to compare v1.03 to v2.0 to give you a better idea when possible.

**ISSUE 1:** _(Resolved. See below.)_
_v1.03_: No Login issues or bugs that I have seen.
_V2.0_: Typing an incorrect password with a length greater than the default "3 characters" doesn't resolve with a visible error that the client can see, such that v1.03 did with an "Incorrect Credentials", for example.

**ISSUE 2**: _(Resolved. See below.)_
_v1.03_: I used a custom script that allowed the user to press TAB to skip to the next input field during login. Within this script, it also allowed the user to hit ENTER/Return to submit the form and thus, login. Worked perfectly.
_v2.0_: Tab functionality still works within my script, however, when you hit ENTER/Return with the incorrect password, it falsely logs in (doesn't authenticate with server, but deactivates the login screen).

**_Request:_** _(No Longer Needed. See Below.)_ Built-in Tab to next input field / Enter to submit form functionality.
See below the reference script that I've been using with no issues until v2.0. (Attach script to whichever canvas/window, but due to it's "OnUpdate" nature, I'd only attach to a canvas or window that would be disabled after completed.)

```
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;

public class InputNavigator : MonoBehaviour
{
    EventSystem system;
    public Button Login;
    private BaseEventData pointer;

    void Start()
    {
        system = EventSystem.current;
    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Tab))
        {
            Selectable next = system.currentSelectedGameObject.GetComponent<Selectable>().FindSelectableOnDown();
            if (next != null)
            {
                InputField inputfield = next.GetComponent<InputField>();
                if (inputfield != null)
                    inputfield.OnPointerClick(new PointerEventData(system));  //if it's an input field, also set the text caret
                    system.SetSelectedGameObject(next.gameObject, new BaseEventData(system));
            }
        }

        if (Input.GetButtonDown("Submit"))
        {
            system.SetSelectedGameObject(Login.gameObject, new BaseEventData(system));
            ExecuteEvents.Execute(Login.gameObject, pointer, ExecuteEvents.submitHandler);
        }
    }
}
```

**ISSUE 3:** _(Resolved. See below.)_
_v2.0:_ Calling Msf.Client.Auth.LogOut(); does not properly log the client out. Client is unable to log back in without restarting client.exe or reloading editor.
_v1.03:_ No issues calling Auth.LogOut();. Works perfectly.

**ISSUE 4:** _(Resolved. See below.)_
v2.0: Upon a user disconnecting from a lobby, GameMaster status is not updated properly to the current GameMaster on the client side only.

***I'll continually update this post as I find more bugs/errors/requests.***

**Comment by alvyxaz** [comment]
**FIX TO ISSUE 1: **

I've left a wrong comparison (should have been equals, instead of not equals). Here's a quick fix: `LoginUi.cs`, line is ~136. It will be included to the next update (**V2.0.2**)

![image](https://cloud.githubusercontent.com/assets/3227731/24091777/d9fd0418-0d52-11e7-9403-4faeea8a8e42.png)

**Comment by alvyxaz** [comment]
**REGARDING ISSUE NR 2**:

I'm not sure if it's worth handling input events in the official release by default, mainly because users might have other functionality planned for Tab / Enter, while the window is still visible.

UI components, that come with the framework, are mostly there as examples, so in this case, since you need some custom handling, it might be easier and faster to write your own UI form for logging in, and call the API method, like this:

``` C#
Msf.Client.Auth.LogIn(Username.text, Password.text, (accountInfo, error) =>
{
    if (accountInfo == null)
    {
        // Failed to log in
        Logs.Error(error);
        return;
    }

    // Successfully logged in
});
```

This is a preferred method, because it gives full control to the developer, and makes sure your UI never changes. For example, if in some update I change the login prefab into something you don't like, you don't have to worry about going through scenes and changing things back (if they were overwritten during the update)

Let me know what you think about this :)

**Comment by DeadlyCobraXXX** [comment]
Thank you for the login fix (Issue 1)! And I agree with what you said about the custom UI (Issue 2). I'll call the API and rewrite my code for the input settings :)

**Comment by DeadlyCobraXXX** [comment]
**Issue 1:** Resolved. Applied fix above. Works perfectly.
**Issue 2:** Resolved. Slightly rewrote my code for API and works perfectly.

**New Issue:**
**Issue 3:** _v2.0:_ Calling Msf.Client.Auth.LogOut(); does not properly log the client out. Client is unable to log back in without restarting client.exe or reloading editor.
_v1.03:_ No issues calling Auth.LogOut();. Works perfectly.

**Comment by alvyxaz** [comment]
Logout functionality failed, because when reconnecting, "Disconnected" event was not called. Fix will be in the V2.0.2 update.  Here are the pictures of the changes I made to fix the issue: 

![image](https://cloud.githubusercontent.com/assets/3227731/24138673/d9a02200-0e21-11e7-8fff-46984d5245de.png)

![image](https://cloud.githubusercontent.com/assets/3227731/24138711/fa5c6ef4-0e21-11e7-884e-dcd0dd4d70b9.png)

I probably should not have rushed so much with the release of V2 :/

**Comment by RowellKataan** [comment]
> I probably should not have rushed so much with the release of V2 

Don't sweat it.  It's difficult to judge the correct time to release, especially when there are a lot of users asking for the new version; despite what state it's in.

**Comment by DeadlyCobraXXX** [comment]
The logout issue was still broken due to a missing line in code. After your fix above and this, it works perfectly.
![](http://i.imgur.com/miupR7A.png)

**Comment by DeadlyCobraXXX** [comment]
Also, I brought back a short code from v1.0.3 to v.2.0 that disabled the MsfHud outside of editor. I think it's an excellent idea to keep implemented in the real version of MSF.

**_MsfHud.cs_**
![](http://i.imgur.com/RfZ1eKB.png)
![](http://i.imgur.com/ollslcu.png)

**Comment by alvyxaz** [comment]
@DeadlyCobraXXX I've added the `EditorOnly` for the next update ;). 

And thanks a lot for catching the `IsLoggedIn` reset. I'm not sure how I've managed to get through it when testing my fix, haha

**Comment by alvyxaz** [comment]
@RowellKataan Thanks for understanding! A week before the release, I got stuck with the development, and with all the e-mails and requests I've been receiving, it was like a nightmare which I thought would never end 😄 . I'm still not sure if I got "my ducks in a row" yet, haha

**Comment by DeadlyCobraXXX** [comment]
I think I found another bug, but I'm not sure if this was due to the nature of the way I have my framework setup or if it is actually across the board in everyone's framework, but...
In a lobby, if you have two or more clients in the lobby and the GameMaster leaves the lobby, the ServerHost assigns a new GameMaster. However, the client-side isn't fully aware of the GameMaster's usernname change. I fixed it here.

![](http://i.imgur.com/ZMdolPf.png)

**Comment by alvyxaz** [comment]
@DeadlyCobraXXX Thanks for catching this!

I've made a change in `JoinedLobby.HandleLobbyMasterChangeMsg`:
![image](https://cloud.githubusercontent.com/assets/3227731/24304457/1a053acc-10c2-11e7-85ac-9783dfbf5b1e.png)

It will be available with the V2.0.2 update

**Comment by DeadlyCobraXXX** [comment]
Thank you! I'll adjust my changes to reflect yours, too.

**Comment by DeadlyCobraXXX** [comment]
All of these issues/bugs were resolved. Thank you. I am going to close this thread and reopen a new one should I find any more.
