### ISSUE TITLE
RSA key size

### ISSUE THREAD

**Issue by tertle** [alvyxaz/barebones-masterserver#6]
It appears you're using a RSA key size of 512bits for the AES key exchange (BmSecurity.cs line 35)

512 is considered extremely weak for a RSA key, even 1024 isn't really acceptable anymore and industry standards have moved to 2048

**Comment by alvyxaz** [comment]
Hey!

Yeah, I'm aware of this.

I've kept it to 512 bits mainly because of two reasons - to reduce CPU load (1024 bytes is considerably slower), and because I doubt anyone would care enough to break a 512bits RSA key to get a password for a simple gaming account. 

It might be my skewed view on security, but the way I think about it - chances of someone sniffing a packet * chances of someone wanting to break a 512bits RSA = quite low. And even if someone "breaks through", it's not a bank account.

However, I understand that it's not fair to "enforce" this view on other developers, so I can add an option to change this to 1k and 2k :)

**Comment by tertle** [comment]
I understand the logic, but I tend to err on the side of caution as my expertise is actually information security, I just happen to be working in game development at the time.

My concern stems from that it currently takes between 4 and 7 hours at a cost of $75-100 using AWS to break RSA512 (and will continue to come down.) Now if users were good and used unique passwords, this wouldn't be such a concern because as you said, it's really only a game but people are terrible and re-use passwords everywhere. 

Email is often included in registration so if they've re-used their password an attacker now has access to their email. Once someone has access to your email, they pretty much have access to everything. nearly everything including banks  still use email to reset passwords. An attacker could also easily mascaraed as the user and easily social engineer their contacts.


As for performance. From my quick look, it appears the RSA key is generated on client, public key sent to master server which is used to encrypt a symmetric key (AES) to send back to client. This is decrypted by client and used for further communication [please correct me if I'm wrong, I only had a brief look.] 

This means that 
a) asymmetric encryption is only used once per connection 
b) the master server only performs encryption, not decryption

As encryption is ~35-60x faster than decryption with RSA (e is usually much smaller than d) the actual increase in CPU load should mostly be restricted to client rather than server.

**Comment by alvyxaz** [comment]
Yeah, I guess adding an option to change the size the key is the best solution.

You're right about the flow of key exchange / serialization.  On WebGL client, when generating a 1024 key, it freezes for 5-10 seconds, which is not very acceptable, but again, this can be mitigated with a variable key size.

Thanks for the suggestion, I'm marking this as an improvement, and I'll include it to the release of V1.03

**Comment by alvyxaz** [comment]
V1.03, via static variable `BmSecurity.RsaKeySize` ;)
