### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by jujugy** [alvyxaz/barebones-masterserver#62]
Hi Alvyxaz,
I found the CPU usage is different between demo v1.03 and v2.01
In the condition of 1 Master, Spawner server & 1 Client.
The v1.03 usage is around 15% and lower;
but the v2.01 is near 90%.
Is there any way to reduce the CPU usage or is there something wrong?

**Comment by alvyxaz** [comment]
Hey! 

In V1.03, I had an FPS cap, which was removed on V2.0, because I thought that it should be up to developers to set the limit to what feels right to them.

I made a quick entry in the documentation.

https://github.com/alvyxaz/barebones-masterserver/wiki/Performance-Considerations

By the way, you're the second person asking me this, so I'll probably reconsider it and reintroduce the default limit back to the framework :)

**Comment by jujugy** [comment]
I got it, thanks.
Maybe  you can put it in the page of important stuff  :P
