### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by jstoeffler** [alvyxaz/barebones-masterserver#66]
Hi,

Thank you for this great project, it is going to be very useful to me!
At the moment I'm quite stuck, and the documentation doesn't seem complete.

I followed the PDF documentation and I managed to have a working client/server build.

Now I would like to have two different builds: one for the client and one for the server.

So here is my Server Scene:

![Imgur](http://i.imgur.com/Ei3bQeP.png)

It seems to work, because when I run it with `./Server -bmMaster` I get this :

![Imgur](http://i.imgur.com/vBXTwT1.png)

And here is my client (I would like to use Unet):

![Imgur](http://i.imgur.com/TFYTz8w.png)

But when I run the client (from the editor), it doesn't connect to the server.

![Imgur](http://i.imgur.com/J4bRSsX.png)

I guess it is because the UnetConnector does "Auto Join if Host" and this is not the host, is it correct ? So how can I auto-join a Unet game ?

Also please fix the documentation:

- It is ./Server -bmMaster and not  ./Server -msfStartMaster like you say in https://github.com/alvyxaz/barebones-masterserver/wiki/Getting-Started
- I think you have to change the "Master Clients Port" in the UnetConnector to match the MasterServer "Client Port" but it was not specified in the doc (I had to guess it)
- I think a more complete documentation is needed and urgent. Are you soon finished with the "From Scratch" ?
- The "ConnectionToMaster" prefab in https://github.com/alvyxaz/barebones-masterserver/wiki/Getting-Started does not seem to exist anymore. It is very confusing to have documentation that talks bout things that don't exist.

Some suggestions:
- The "Only In Editor" features are a bit annoying, because for my game I need to have 2 players, so I need to work with a build of the game that's not in the editor, and nothing works like the editor version. I think we can disable them by ourself when we want, or create our own flags to match our configuration.
- "Scene to switch to after disconnect" -> Maybe we want to try to auto-reconnect ?

**Comment by alvyxaz** [comment]
Hey!

I'm not sure if you've noticed, but you're using V1.03 version of the framework, and the documentation you're refering to is for V2.0. 

There's a warning in documentation which says that if you download the asset from asset store, V2.0 is included as a separate .unitypackage as "Barebones/MSF V2.0.x.unitypackage". I did it this way to give time for users of earlier version to either switch, and to avoid overwriting their projects if they are not aware of the V2.0 at all.

Can you send me an e-mail to "alvyxaz@gmail.com", and I'll send you V2.0.2 (which I've finished today). It contains a "Quick Setup" demo, which might help you to get started on your project a lot faster, and I think it will solve some of your issues.

By the way, I'm really sorry about the inconveniences this has caused you. I wonder if there are more people who are not aware about the V2.0 being in a separate .unitypackage. I'll add big notifications in the asset itself, so that we can avoid this in the future

**Comment by jstoeffler** [comment]
> I'm not sure if you've noticed, but you're using V1.03 version of the framework, and the documentation you're refering to is for V2.0.

Oh... so that's why I've been struggling !!!
