### ISSUE TITLE
UnetGameRoom and NetworkBehaviour v1 to v2

### ISSUE THREAD

**Issue by tatien** [alvyxaz/barebones-masterserver#71]
Hi,
I'm updating my GameServer from MSF v1 to v2 and I'm facing some issue, it's about UnetGameRoom who extend NetworkBehaviour and force to use NetworkIdentity. 
In the V1 I didn't use any of the NetworkIdentity and I didn't want to have them ( I have nothing in commun between my clients and my gameRoom, every communication is call by scripts). 

Can I use the V2 without using NetworkBehaviour and NetworkIdentity ?

**Comment by alvyxaz** [comment]
Hey!

Yeah, you can still use V2 - UnetGameRoom is just an example for those, who use Unet HLAPI.

What `UnetGameRoom` does - it waits for the NetworkManager to start the server (this is when `NetworkBehaviour.OnStartServer is called), and the calls `Msf.Server.Rooms.RegisterRoom`.

I used NetworkBehaviour so that I wouldn't have to write a custom NetworkManager with events.

You can register the room manually, check this out:
https://github.com/alvyxaz/barebones-masterserver/wiki/API-examples.-Rooms

**Comment by tatien** [comment]
Thank you !! 👍
